# Generated by Django 4.2.11 on 2024-03-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_logs',
            old_name='username',
            new_name='user_id',
        ),
    ]
